@echo off
echo Starting Cube Buildathon 01 - Receiving Manager...
echo Starting FastAPI Backend on http://localhost:8000 ...
start python start_server.py
cd frontend
echo Starting Frontend Development Server on http://localhost:3000 ...
npm run dev
